PROPERTY_TERMS = [
    "hardness",
    "color",
    "streak",
    "luster",
    "lustre",
    "cleavage",
    "transparency",
    "crystal structure",
    "crystal system",
    "density",
    "specific gravity",
    "brittle",
    "flexible",
    "elastic",
    "magnetic",
    "radioactive",
    "fluorescent",
    "conductive",
    "refractive index",
]
USE_TERMS = [
    "jewelry",
    "mining",
    "metal extraction",
    "industrial mineral",
    "ceramics",
    "cement",
    "glass manufacturing",
    "abrasive",
    "pigment",
    "fertilizer",
    "construction material",
    "electronics",
    "battery",
    "semiconductor",
    "solar cell",
    "radiation shielding",
    "chemical production",
    "water treatment",
    "catalyst",
    "research",
    "geological indicator",
    "carving",
]
GROUP_TERMS = [
    "silicate",
    "carbonate",
    "oxide",
    "sulfide",
    "sulfate",
    "phosphate",
    "borate",
    "halide",
    "native element",
]
